# Generated by Django 3.2.5 on 2021-07-10 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expidition_succeed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MatchResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_thrall', models.BooleanField()),
                ('score', models.PositiveSmallIntegerField()),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.gamesession')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.player')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.role')),
            ],
        ),
        migrations.AddField(
            model_name='gamesession',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.map'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='players',
            field=models.ManyToManyField(to='api.Player'),
        ),
    ]
