# Generated by Django 3.2.5 on 2021-07-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gamesession',
            table='game_sessions',
        ),
        migrations.AlterModelTable(
            name='map',
            table='maps',
        ),
        migrations.AlterModelTable(
            name='matchresults',
            table='match_results',
        ),
        migrations.AlterModelTable(
            name='player',
            table='players',
        ),
        migrations.AlterModelTable(
            name='role',
            table='roles',
        ),
    ]
