# Generated by Django 3.2.5 on 2021-07-10 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210710_1754'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatchResults',
            new_name='MatchResult',
        ),
        migrations.AlterModelOptions(
            name='gamesession',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='map',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='matchresult',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelTable(
            name='matchresult',
            table='match_result',
        ),
    ]
