# Generated by Django 3.2.5 on 2021-07-10 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210710_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='created',
            field=models.DateField(auto_created=True, default=datetime.datetime(2021, 7, 11, 0, 42, 52, 471110)),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 11, 0, 42, 52, 471110)),
        ),
    ]
