# Generated by Django 3.2.5 on 2021-07-11 11:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210711_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='created',
            field=models.DateField(auto_created=True, default=datetime.datetime(2021, 7, 11, 11, 24, 6, 633083, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 11, 11, 24, 6, 633083, tzinfo=utc)),
        ),
        migrations.AlterModelTable(
            name='matchresult',
            table='match_results',
        ),
    ]
