# Generated by Django 3.2.5 on 2021-07-11 22:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210711_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='classic_rules',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='created',
            field=models.DateField(auto_created=True, default=datetime.datetime(2021, 7, 11, 22, 8, 23, 85471, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 11, 22, 8, 23, 85471, tzinfo=utc)),
        ),
    ]
